### ISSUE TITLE
gLabel TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by trvadams** [pFindStudio/pGlyco3#42]
Hello,

I am trying to generate annotated MS2s after a successful pGlyco search. However, I'm getting an error when trying to load the .raw file:

`Traceback (most recent call last):
  File "gLabel-GP.py", line 1417, in OnMGFButton
  File "gLabel-GP.py", line 471, in ReadMGF
TypeError: 'NoneType' object is not callable`

This seems to trip up the program and doesn't allow the annotation to proceed after loading the pGlycoRes file and hitting 'Batch plot':

`[START] 1th GPSM: BG505_tryp.1067.1067.2.2.dta
Traceback (most recent call last):
  File "gLabel-GP.py", line 1407, in OnBatchPlotButton
  File "gLabel-GP.py", line 1203, in save_plot
AttributeError: 'NoneType' object has no attribute 'Has_Spec'`

I've tested it on old .raw files that have worked fine previously and get the same output. Is anyone else able to reproduce this?

Best,
Trevor

**Comment by jalew188** [comment]
ReadMGF() gets a None, this must be the raw access issue..., can you share the raw data?
