### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DARA-MSdata\\pglyco' 从一开始就找不到数据了，请问是储存路径的问题吗？

### ISSUE THREAD

**Issue by ZiqingChan** [pFindStudio/pGlyco3#50]
报错如下，请曾老师帮忙看一下，感谢！
Already registered!
[pGlyco Info] Save cfg as `D:\DARA-MSdata\pglyco outputdata\pGlyco.cfg`
[pGlyco] Starting task ...
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>rem ***************************************************
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>parse_raw.exe "D:\DARA-MSdata\pglyco"
Process ID=48556: Traceback (most recent call last):
Process ID=48556:   File "parse_raw.py", line 162, in <module>
Process ID=48556:   File "parse_raw.py", line 94, in __init__
Process ID=48556:   File "pGlyco_config.py", line 48, in __init__
Process ID=48556:   File "pGlyco_config.py", line 76, in read_cfg
Process ID=48556: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DARA-MSdata\\pglyco'
Process ID=48556: [48336] Failed to execute script 'parse_raw' due to unhandled exception!
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>pGlycoDB.exe "D:\DARA-MSdata\pglyco"
Process ID=48556: *****************************************************
Process ID=48556: *                                                   *
Process ID=48556: *              * Welcome to pGlyco3 *               *
Process ID=48556: *                                                   *
Process ID=48556: *               * pglyco@ict.ac.cn *                *
Process ID=48556: *                                                   *
Process ID=48556: *****************************************************
Process ID=48556: [pGlyco] pGlyco software will be expired in 2027/01/01
Process ID=48556: [pGlyco Error] ReadConfig() in BasicIOFunction.cpp: could not open D:\DARA-MSdata\pglyco
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>gpPercolator.exe -p "D:\DARA-MSdata\pglyco"
Process ID=48556: 'gpPercolator.exe' ??????????????????????????????????????
Process ID=48556: ??????????????
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>pGlycoFDR.exe -p "D:\DARA-MSdata\pglyco"
Process ID=48556: ??????????
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>pGlycoProInfer.exe -p "D:\DARA-MSdata\pglyco"
Process ID=48556: Traceback (most recent call last):
Process ID=48556:   File "pGlycoProInfer.py", line 162, in <module>
Process ID=48556:   File "pGlyco_config.py", line 48, in __init__
Process ID=48556:   File "pGlyco_config.py", line 76, in read_cfg
Process ID=48556: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DARA-MSdata\\pglyco'
Process ID=48556: [32012] Failed to execute script 'pGlycoProInfer' due to unhandled exception!
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>XIC.exe -p "D:\DARA-MSdata\pglyco"
Process ID=48556: Traceback (most recent call last):
Process ID=48556:   File "XIC.py", line 463, in <module>
Process ID=48556:   File "XIC.py", line 82, in __init__
Process ID=48556:   File "pGlyco_config.py", line 48, in __init__
Process ID=48556:   File "pGlyco_config.py", line 76, in read_cfg
Process ID=48556: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DARA-MSdata\\pglyco'
Process ID=48556: [43660] Failed to execute script 'XIC' due to unhandled exception!
Process ID=48556: [XIC] Smoothing window = 21
Process ID=48556: [XIC] Smoothing method = savgol_filter
Process ID=48556: D:\DARA-MSdata\pGlyco3.1\pGlyco3.1>pGlycoSite.exe "D:\DARA-MSdata\pglyco"
Process ID=48556: ??????????
[pGlyco] <Error> File D:\DARA-MSdata\pglyco outputdata\process1\pGlycoDB-GP-FDR.txt does not exist!
[pGlyco] <Error> File D:\DARA-MSdata\pglyco outputdata\process1\pGlycoDB-GP-FDR-Pro.txt does not exist!
[pGlyco] <Error> File D:\DARA-MSdata\pglyco outputdata\process1\pGlycoDB-GP-FDR-Pro-Quant.txt does not exist!
[pGlyco] <Error> File D:\DARA-MSdata\pglyco outputdata\process1\pGlycoDB-GP-FDR-Pro-Quant-Site.txt does not exist!
[pGlyco] All results are merged!
[pGlyco] Running time = 0.6 minutes.

**Comment by jalew188** [comment]
应该是因为路径有空格

**Comment by ZiqingChan** [comment]
> 应该是因为路径有空格

感谢解答，运行过程中出现以下报错，请问是什么问题导致的呢？影响后续分析吗？请见附件1、2。
运行gLabel时，这一项Spectrum应该如何操作呢？请见附件3。
我的quant-site.txt中内容比较少，甚至不如上面几个txt，按照guide选取这个用作分析是没问题的嘛？
User guide中Python用于后分析的两个链接都显示404page not found，请问我可以从哪里获取？
糖基化分析小白，问题较多，盼曾老师解答，谢谢！！
![1](https://github.com/user-attachments/assets/9fdb7ea9-d75c-40d8-8fa3-445b915a68f3)
![2](https://github.com/user-attachments/assets/71135be2-fcd7-4932-b635-b666bbad12fa)
![3](https://github.com/user-attachments/assets/3f9836cf-872b-43eb-ae36-40f795dce14c)
![4](https://github.com/user-attachments/assets/02662fe0-be5b-4e61-acd8-3f85e608609c)

**Comment by SRS-123** [comment]
您好，我想请教一下，您gLabel for glycopeptide这里输入的MGF文件是您自己转换的，还是第一步生成的啊

**Comment by SRS-123** [comment]
> > 应该是因为路径有空格
> 
> 感谢解答，运行过程中出现以下报错，请问是什么问题导致的呢？影响后续分析吗？请见附件1、2。 运行gLabel时，这一项Spectrum应该如何操作呢？请见附件3。 我的quant-site.txt中内容比较少，甚至不如上面几个txt，按照guide选取这个用作分析是没问题的嘛？ User guide中Python用于后分析的两个链接都显示404page not found，请问我可以从哪里获取？ 糖基化分析小白，问题较多，盼曾老师解答，谢谢！！ ![1](https://github.com/user-attachments/assets/9fdb7ea9-d75c-40d8-8fa3-445b915a68f3) ![2](https://github.com/user-attachments/assets/71135be2-fcd7-4932-b635-b666bbad12fa) ![3](https://github.com/user-attachments/assets/3f9836cf-872b-43eb-ae36-40f795dce14c) ![4](https://github.com/user-attachments/assets/02662fe0-be5b-4e61-acd8-3f85e608609c)

您好，请问解决这个问题了吗
